name: slimepad
version: ${project.version}
main: me.themondon.slimepad
authors: [TheMonDon]
description: slime block jump pads
website: https://www.crafters-island.com
commands:
  slimepad:
    description: Slimepad command
    aliases: [sp, spad. daddy]
