name: SlimePad
version: ${project.version}
main: me.TheMonDon.SlimePad
authors: [TheMonDon]
description: slime block jump pads
website: https://www.crafters-island.com
commands:
  slimepad:
    description: SlimePad command
    aliases: [sp, spad, daddy]
  slimepad-reload:
    description: SlimePad reload command
    permission: sp.reload
    permission-message: You do not have access to sp.reload
    aliases: [spreload, spr]